ranks:
  - "owner"
  - "co-owner"
  - "manager"
  - "developer"
  - "admin"
  - "srmod"
  - "mod"
  - "t-mod"
  - "helper"

discord:
  webhook: "https://discord.com/api/webhooks/1348082210841952268/DN3bI0Q_JBDfmi-qsYOBY6Kh5KquiACYMffxLLDe6YeckM3g1OjO2ar7yfkTIUmsJdra"
  embeds:
    rank_update:
      content: "" # Shows out of embed
      title: "🔮 | Rank Updated"
      description: "**Player:** `<player>` \n **Previous Rank:** `<previousRank>` \n **New Rank:** `<newRank>` \n **Temporary:** `<isTemporary>`" # Shows in embed
      color: 15105570 # Embed color
      author: "" # Author of embed
      author_url: "" # When clicking author
      author_icon: "" # Author icon
      footer: "© | PromoteManager" # Footer of embed
      footer_icon: "https://imgur.com/a/kdFrqpy" # Footer icon of embed
      thumbnail: "" # Icon on the right of embed
    player_permission_add:
      content: "" # Shows out of embed
      title: "🔮 | Permission Added"
      description: "**Player:** `<player>` \n **Permission:** `<permission>` \n **Temporary:** `<isTemporary>`" # Shows in embed
      color: 2817792 # Embed color
      author: "" # Author of embed
      author_url: "" # When clicking author
      author_icon: "" # Author icon
      footer: "© | PromoteManager" # Footer of embed
      footer_icon: "https://imgur.com/a/kdFrqpy" # Footer icon of embed
      thumbnail: "" # Icon on the right of embed
    player_permission_remove:
      content: "" # Shows out of embed
      title: "🔮 | Permission Removed"
      description: "**Player:** `<player>` \n **Permission:** `<permission>`" # Shows in embed
      color: 16711680 # Embed color
      author: "" # Author of embed
      author_url: "" # When clicking author
      author_icon: "" # Author icon
      footer: "© | PromoteManager" # Footer of embed
      footer_icon: "https://imgur.com/a/kdFrqpy" # Footer icon of embed
      thumbnail: "" # Icon on the right of embed